dayfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('df_user.urls', namespace='user')),
    url(r'^', include('df_goods.urls', namespace='goods')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),
    url(r'^order/', include('df_order.urls', namespace='order')),
    url(r'^search/', include('haystack.urls')),
]

df_cart/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.cart, name='subcart'),
    url(r'^add(\d+)_(\d+)/', views.add, name='add'),
    url(r'^edit(\d+)_(\d+)/', views.edit, name='edit'),
    url(r'^delete(\d+)/', views.delete, name='delete'),
]

df_user/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^login_handle/', views.login_handle, name='login_handle'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^info/', views.info, name='info'),
    url(r'^order(\d+)/', views.order, name='order'),
    url(r'^site/', views.site, name='site'),
    url(r'^register/', views.register, name='register'),
    url(r'^register_handle/', views.register_handle, name='register_handle'),
    url(r'^register_exist/', views.register_exist, name='register_exist'),
]

df_order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=8, decimal_places=2)
    oaddress = models.CharField(max_length=150)
    user = models.ForeignKey('df_user.UserInfo')

class OrderDetailInfo(models.Model):
    price = models.DecimalField(max_digits=8, decimal_places=2)
    count = models.IntegerField()
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey('OrderInfo')

df_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)

class UserAddress(models.Model):
    ureceiver = models.CharField(max_length=20)
    uaddress = models.CharField(max_length=100)
    upostcode = models.CharField(max_length=6, default='')
    uphone = models.CharField(max_length=11)
    user = models.ForeignKey('UserInfo')

df_user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from hashlib import sha1
import json
from models import *
from df_goods.models import *
from df_order.models import *
import login_check
from django.core.paginator import Paginator,Page


def register(req):
    titile = {'title': '天天生鲜-注册页面'}
    return render(req, 'df_user/register.html', titile)

def register_handle(req):
    print req
    if req.method == 'POST':
        post = req.POST
        uname = post.get('user_name')
        upwd = post.get('pwd')
        uemail = post.get('email')
        s1 = sha1()
        s1.update(upwd)
        upwd0 = s1.hexdigest()

        user = UserInfo()
        user.uname = uname
        user.upwd = upwd0
        user.uemail = uemail
        user.save()

        return redirect('/user/login/')
    return redirect('/user/register/')

def register_exist(req):
    name = req.GET.get('user_name', None)
    email = req.GET.get('email', None)
    if name:
        count0 = UserInfo.objects.filter(uname=name).count()
        tmp0 = json.dumps({'count': count0})
        return HttpResponse(tmp0)
    elif email:
        count1 = UserInfo.objects.filter(uemail=email).count()
        tmp1 = json.dumps({'count': count1})
        return HttpResponse(tmp1)

def login(req):
    uname = req.COOKIES.get('uname', '')
    context = {
        'title': '天天生鲜-登录页面',
        'error_name': 0,
        'error_pwd': 0,
        'uname': uname,
    }
    return render(req, 'df_user/login.html', context)

def login_handle(req):
    post = req.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    remember = post.get('remember')
    user = UserInfo.objects.filter(uname=uname)
    if len(user):
        s1 = sha1()
        s1.update(upwd)
        if s1.hexdigest() == user[0].upwd:
            # Redirect不能设置Cookie，所以引入HttpResponse的子类HttpResponseRedirect
            red = HttpResponseRedirect('/')
            if remember == 1:
                red.set_cookie('uname', uname)
            else:
                # max_age=-1表示Cookie立即失效
                red.set_cookie('uname', '', max_age=-1)
            req.session['user_id'] = user[0].id
            req.session['user_name'] = uname
            return red
        else:
            context = {
                'title': '天天生鲜-登录页面',
                'error_name': 0,
                'error_pwd': 1,
                'uname': uname,
                'upwd': upwd,
            }
            return render(req, 'df_user/login.html', context)
    else:
        context = {
            'title': '天天生鲜-登录页面',
            'error_name': 1,
            'error_pwd': 0,
            'uname': uname,
            'upwd': upwd,
        }
        return render(req, 'df_user/login.html', context)

def logout(req):
    req.session.flush()
    return redirect('/')

@login_check.login
def info(req):
    user_email = UserInfo.objects.get(id=req.session['user_id']).uemail
    address = UserAddress.objects.filter(user=req.session['user_id'])
    if address.count() == 0:
        user_phone = ''
        user_address = ''
    else:
        user_phone = address[0].uphone
        user_address = address[0].uaddress
    goods_ids = req.COOKIES.get('goods_ids', '')
    goods_id_list = goods_ids.split(',')
    goods_list = []
    if goods_id_list[0] != '':
        for goods_id in goods_id_list:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    context = {
        'title': '天天生鲜-用户中心',
        'subtitle': '用户中心',
        'user_name': req.session['user_name'],
        'user_email': user_email,
        'user_phone': user_phone,
        'user_address': user_address,
        'goods_list': goods_list,
    }
    return render(req, 'df_user/user_center_info.html', context)

@login_check.login
def order(req, pindex):
    order_list = OrderInfo.objects.filter(user_id=req.session['user_id']).order_by('-oid')
    paginator = Paginator(order_list,  2)
    if pindex == '':
        pindex = '1'
    page = paginator.page(int(pindex))
    context = {'title': '天天生鲜-用户中心',
               'subtitle': '用户中心',
               'paginator': paginator,
               'page': page,
               }
    return render(req, 'df_user/user_center_order.html', context)

@login_check.login
def site(req):
    tmp = UserAddress.objects.filter(user=req.session['user_id'])
    address = UserAddress() if tmp.count()==0 else tmp[0]
    if req.method == 'POST':
        post = req.POST
        address.ureceiver = post.get('ureceiver')
        address.uaddress = post.get('uaddress')
        address.upostcode = post.get('upostcode')
        address.uphone = post.get('uphone')
        address.user_id = req.session['user_id']
        address.save()
    context = {'title': '天天生鲜-用户中心', 'subtitle': '用户中心', 'address': address}
    return render(req, 'df_user/user_center_site.html', context)

templates/df_user/base_user_header.html
{% extends 'base_footer.html' %}

{% block content1 %}

    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.user_name|default:'' != '' %}
				<div class="login_info fl" style="display: block">
					欢迎您：<em>{{ request.session.user_name }}</em>
                    <span>|</span>
                    <a href="/user/logout/"  style="color: #666">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl" style="display: block">
					<a href="/user/login/">登录</a>
					<span>|</span>
					<a href="/user/register/">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order1/">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ subtitle }}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

    {% block content2 %}
    {% endblock content2 %}

{% endblock content1 %}

templates/df_user/login.html
{% extends 'base_footer.html' %}

{% block header %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
        $(function () {
            user_error = true;
            pwd_error = true;
            if( {{ error_name }} == 1 ){
                $('.user_error').html('用户名错误').show();
            }
            if( {{ error_pwd }} == 1) {
                $('.pwd_error').html('密码错误').show();
            }
            $('.name_input').blur(function () {
                check_name();
            });
            $('.pass_input').blur(function () {
                check_pwd();
            });

            function check_name() {
                if($('.name_input').val().length == 0){
                    $('.user_error').html('用户名为空').show();
                    user_error = true;
                }else {
                    $('.user_error').hide();
                    user_error = false;
                }
            };
            function check_pwd() {
                if($('.pass_input').val().length == 0){
                    $('.pwd_error').html('密码为空').show();
                    pwd_error = true;
                }else {
                    $('.pwd_error').hide();
                    pwd_error = false;
                }
            };

            $('form').submit(function () {
                check_name();
                check_pwd();
                if(user_error == false && pwd_error == false){
                    return true;
                }else {
                    return false;
                }
            });
        })
    </script>
{% endblock header %}

{% block content1 %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1" checked="checked">
							<label for="remember">记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content1 %}

templates/df_user/register.html
{% extends 'base_footer.html' %}

{% block header %}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock header %}

{% block content1 %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form id="reg_form" action="/user/register_handle/" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label for="user_name">用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label for="pwd">密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label for="cpwd">确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label for="email">邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label for="allow">同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock content1 %}

templates/df_user/user_center_info.html
{% extends 'df_user/base_user_header.html' %}
{% block content2 %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order1/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user_name }}</li>
							<li><span>联系邮箱：</span>{{ user_email }}</li>
                            <li><span>联系电话：</span>{{ user_phone }}</li>
							<li><span>联系地址：</span>{{ user_address }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                {% for goods in goods_list %}
				<li>
					<a href="/{{ goods.id }}/"><img src="/static/{{ goods.gpic }}"></a>
					<h4><a href="/{{ goods.id }}/">{{ goods.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.gprice }}</span>
						<span class="unit">{{ goods.gprice }}/{{ goods.gunit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
		</div>
		</div>
	</div>

{% endblock content2 %}

templates/df_user/user_center_order.html
{% extends 'df_user/base_user_header.html' %}
{% block header %}
<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript">
$(function () {
    $('.col04').each(function () {
        num=parseFloat($(this).prev().text());
        price=parseFloat($(this).prev().prev().find('span').text());
        $(this).text(num*price+'元');
    });
});
</script>
{% endblock header %}
{% block content2 %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order1/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% if paginator.count >  0 %}
                    {% for order in page %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">{{ order.odate }}</li>
                        <li class="col02">订单号：{{ order.oid }}</li>
                        <li class="col02 stress">
                            {% if order.oIsPay %}已支付
                            {% else %}未支付
                            {% endif %}
                        </li>
                    </ul>
                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {% for detail in order.orderdetailinfo_set.all %}
                                    <ul class="order_goods_list clearfix">
                                        <li class="col01"><img src="/static/{{ detail.goods.gpic }}"></li>
                                        <li class="col02">{{ detail.goods.gtitle }}<em><span>{{ detail.goods.gprice }}</span>元/{{ detail.goods.gunit }}</em></li>
                                        <li class="col03">{{ detail.count }}</li>
                                        <li class="col04">0元</li>
                                    </ul>
                                    {% endfor %}
                                </td>
                                <td width="15%">{{ order.ototal }}元</td>
                                {% if order.oIsPay %}
                                <td width="15%">已付款</td>
                                <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                                {% else %}
                                <td width="15%">待付款</td>
                                <td width="15%"><a href="/order/pay{{ order.oid }}/" class="oper_btn">去付款</a></td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>
                    {% endfor %}
                    <div class="pagenation">
                    {% if page.has_previous %}
                        <a href="/user/order{{ page.previous_page_number }}"><上一页</a>
                    {% endif %}
                    {% for pindex in paginator.page_range %}
                    {% if pindex == page.number %}
                    <a href="#" class="active">{{ pindex }}</a>
                    {% else %}
                    <a href="/user/order{{ pindex }}">{{ pindex }}</a>
                    {% endif %}
                    {% endfor %}
                    {% if page.has_next %}
                    <a href="/user/order{{ page.next_page_number }}">下一页></a>
                    {% endif %}
                {% else %}
                    暂无订单信息
                {% endif %}
				</div>
		</div>
	</div>

{% endblock content2 %}

templates/df_user/user_center_site.html
{% extends 'df_user/base_user_header.html' %}
{% block content2 %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order1/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ address.uaddress|default:'' }} （{{ address.ureceiver|default:'' }}） {{ address.uphone|default:'' }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ureceiver" value="{{ address.ureceiver|default:'' }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ address.uaddress|default:'' }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="upostcode" value="{{ address.upostcode|default:'' }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ address.uphone|default:'' }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock content2 %}